background = "#fafafa"
border_fg = "#b0b0b0"
text_fg = "#202020"
dimmed_text_fg = "#888888"
input_text_fg = "#202020"
result_count_fg = "#888888"
result_name_fg = "#202020"
result_line_number_fg = "#b0b0b0"
result_value_fg = "#888888"
selection_fg = "#202020"
selection_bg = "#f0f0f0"
match_fg = "#5182a4"
preview_title_fg = "#888888"
channel_mode_fg = "#fafafa"
channel_mode_bg = "#888888"
remote_control_mode_fg = "#fafafa"
remote_control_mode_bg = "#b0b0b0"
action_picker_mode_fg = "#fafafa"
action_picker_mode_bg = "#b0b0b0"
send_to_channel_mode_fg = "#888888"
